CREATE TABLE k8s_events (
    id bigserial PRIMARY KEY,
    level TEXT,
    audit_id TEXT,
    stage TEXT,
    request_uri TEXT,
    verb TEXT,
    username TEXT,
    usergroups TEXT,
    source_ips TEXT,
    user_agent TEXT,
    request_time bigint,
    pod_name TEXT,
    pod_namespace TEXT,
    container_name TEXT,
    container_image TEXT,
    container_arguments TEXT,
    container_exec_command TEXT,
    stdout TEXT,
    stderr TEXT,
    raw_object_ref TEXT,
    raw_request_object TEXT,
    raw_response_object TEXT
);
